Repository brjx/simpleapp, pull requests merged in 2019-05, with the labels that each got.

#1 adds prometheus metrics endpoint and scraping
  charts/simpleapp/values.yaml
  pom.xml
  src/main/java/wtf/brzhk/simpleapp/DemoApplication.java
  src/main/resources/application.properties
Labels: approved, lgtm, size/M

#2 adds chart source
  charts/simpleapp/Chart.yaml
Labels: approved, lgtm, size/XS

#3 adds chart icon
  charts/icon128x128.png
  charts/preview/Chart.yaml
  charts/simpleapp/Chart.yaml
  src/main/java/wtf/brzhk/simpleapp/DemoApplication.java
  src/test/java/wtf/brzhk/simpleapp/DemoApplicationTests.java
  watch.sh
Labels: approved, lgtm, size/S

#4 adds github.com external service declaration
  charts/simpleapp/templates/github-endpoint.yaml
  charts/simpleapp/templates/github-service.yaml
Labels: approved, size/M

#6 Feature/other extsvc
  charts/simpleapp/templates/github-endpoint.yaml
  charts/simpleapp/templates/github-service.yaml
  src/main/resources/application.properties
Labels: approved, size/M

#7 new UI! WOW
  src/main/java/wtf/brzhk/simpleapp/DemoApplication.java
Labels: approved, size/XS
